import type { NextPage } from "next";
import Head from "next/head";
import { useUser } from "@auth0/nextjs-auth0";
import { withPageAuthRequired } from "@auth0/nextjs-auth0";
import useSWR from "swr";
import { fetcher } from "../utils/helper";

const Profile: NextPage = () => {
  const { user, error, isLoading }: any = useUser();
  useSWR("/api/profile", fetcher);
  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>{error.message}</div>;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome {user.name}! <a href="/api/auth/logout">Logout</a>
        </h1>
      </main>
    </div>
  );
};

export default withPageAuthRequired(Profile);
