import type { NextPage } from "next";
import Head from "next/head";
import { useUser } from "@auth0/nextjs-auth0";
import { withPageAuthRequired } from "@auth0/nextjs-auth0";
import useSWR from "swr";
import { fetcher } from "../utils/helper";
import Link from "next/link";
const Profile: NextPage = () => {
  const { user, error, isLoading }: any = useUser();
  useSWR("/api/profile", fetcher);
  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>{error.message}</div>;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome {user.name}!</h1>

        <Link href="/">
          <a className="px-4 py-2 bg-blue-500 text-white rounded my-10">Home</a>
        </Link>
        <a
          href="/api/auth/logout"
          className="px-4 py-2 bg-blue-500 text-white rounded my-10"
        >
          Logout
        </a>
      </main>
    </div>
  );
};

export default withPageAuthRequired(Profile);
